FileUploadWebAPIMVC5/Controllers/LeadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FileUploadWebAPIMVC5.Controllers
{
    public class LeadController : Controller
    {
        // GET: Lead
        public ActionResult Index()
        {
            return View();
        }

        [System.Web.Mvc.HttpGet]
        public ActionResult Comments(string LeadId)
        {
            var vm = new List<Comments>()
            {
                    new Comments() { id = "1", name="test"},
                    new Comments() { id = "2", name="test2"},
                    new Comments() { id = "3", name="test3"}

            };
            return PartialView("_Comments", new Comments() { id = "1", name = "test" });
        }
    }
    public class Comments
    {
        public string id { get; set; }
        public string name { get; set; }
    }
}

FileUploadWebAPIMVC5/Views/Lead/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}

<h2>Index</h2>
<button id="loadComments" class="btn btn-primary">Load comments</button>
<div id="dialog" style="display: none">
</div>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/jquery-ui.js" type="text/javascript"></script>
<link href="http://ajax.aspnetcdn.com/ajax/jquery.ui/1.8.9/themes/blitzer/jquery-ui.css"
      rel="stylesheet" type="text/css" />
<script>
    $(document).ready(function () {
        $("#dialog").dialog({
            autoOpen: false,
            modal: true,
            title: "View Details"
        });
        $("#loadComments").click(function () {
            $.ajax({
                type: "GET",
                url: '@Url.Action("Comments","Lead")',
                data: '{LeadId: "' + 100 + '" }',
                contentType: "application/json; charset=utf-8",
                dataType: "html",
                success: function (response) {
                    $('#dialog').html(response);
                    $('#dialog').dialog('open');
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        });

    });

</script>